// Layout fixture only; this does not mount the desktop Protyle or run a model.
import {ChatView} from '../src/ui';
import type {Attachment} from '../src/context';
import type {ComposerFactory} from '../src/composer';
import {editorCursor,selectEditorRange} from '../src/composer-cursor';
const note={id:'20261001124824-pq6acxs',title:'研究笔记'};
const chat:any={status:'布局预览 · 模拟数据',busy:false,settings:{cwd:'/tmp',model:'gpt-6.1-sol',modelName:'GPT-6.1 Sol',reasoningEffort:'medium',sandbox:'read-only'},session:{id:'composer-preview',title:'新对话',messages:[]},requests:new Map()};
let attachments:Attachment[]=[];
const composer:ComposerFactory=(host,send,change)=>{
 const root=document.createElement('div');root.className='protyle-wysiwyg';const block=document.createElement('div');block.dataset.nodeId='preview';const input=document.createElement('div');input.contentEditable='true';input.style.minHeight='60px';input.style.outline='none';input.setAttribute('aria-label','预览输入框');block.append(input);root.append(block);host.append(root);
 const insert=(html:string)=>{const s=window.getSelection();if(!s?.rangeCount||!root.contains(s.getRangeAt(0).startContainer)){input.focus();selectEditorRange(root,input.textContent!.length,input.textContent!.length);}const range=window.getSelection()!.getRangeAt(0);range.deleteContents();const fragment=range.createContextualFragment(html),last=fragment.lastChild;range.insertNode(fragment);if(last){range.setStartAfter(last);range.collapse(true);}change();};
 input.oninput=change;input.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send();}};
 return {element:root,get value(){return input.textContent||'';},set value(v){input.textContent=v;change();},references:()=>Array.from(input.querySelectorAll<HTMLElement>('[data-type=block-ref]')).map(n=>({id:n.dataset.id!,title:n.textContent!})),focus:()=>input.focus(),destroy:()=>root.remove(),cursor:()=>editorCursor(root),replaceRange(start,end,text){selectEditorRange(root,start,end);const span=document.createElement('span');span.textContent=text;insert(span.innerHTML);},insertReference(ref){const span=document.createElement('span');span.dataset.type='block-ref';span.dataset.id=ref.id;span.dataset.subtype='d';span.textContent=ref.title;insert(span.outerHTML+' ');},insertContent:content=>insert(content.html||content.text),bookmark(){const range=window.getSelection()?.rangeCount?window.getSelection()!.getRangeAt(0).cloneRange():undefined;return()=>{if(range&&root.contains(range.startContainer)){const s=window.getSelection();s?.removeAllRanges();s?.addRange(range);}else selectEditorRange(root,input.textContent!.length,input.textContent!.length);return true;};}};
};
const view=new ChatView(document.getElementById('app')!,()=>chat,{composer,send:async()=>false,stop:()=>{},settings:()=>{},newChat:()=>{},select:()=>{},list:()=>[],attach:()=>[note],drop:async()=>[note],searchNotes:async()=>[note],clear:()=>{attachments=[];view.update();},context:()=>'',attachments:()=>attachments,removeAttachment:i=>{attachments.splice(i,1);view.update();},importMedia:async sources=>{attachments.push(...sources.map(s=>({title:s.title,text:'mock',media:{key:s.key,kind:s.kind,marker:s.marker,path:'/tmp/mock-'+s.title,url:s.kind==='image'?'/image.png':undefined,size:123456}})));view.update();},error:message=>{document.getElementById('notice')!.textContent=message;}});
view.input.value='查看这份文档：';view.input.focus();selectEditorRange(view.input.element,8,8);view.input.insertReference?.(note);
document.getElementById('mixed')!.onclick=()=>{view.input.focus();const e=new ClipboardEvent('paste',{bubbles:true,cancelable:true,clipboardData:new DataTransfer()});e.clipboardData!.setData('text/html','<p><strong>对照示意图</strong><img src="/image.png" alt="输入框示意.png">继续检查引用效果。<a href="assets/实验报告.pdf">实验报告.pdf</a>最后保留结论。</p>');view.input.element.dispatchEvent(e);};
