import {ComposerPopover,modelPanel,effortPanel,permissionPanel} from '../src/popover';
import {workspacePanel} from '../src/workspace-menu';
import {ChatView} from '../src/ui';
import {currentActivityPrompt} from '../src/activity';
const chat:any={status:'界面测试 · 模拟回复',busy:false,settings:{cwd:'/Users/demo/Documents/Codex/2026-10-02/siyuan-preview',model:'gpt-6-astra',modelName:'GPT-6 Astra',reasoningEffort:'medium',sandbox:'read-only'},session:{id:'preview',title:'新对话',workspaceMode:'auto',messages:[]},contextUsageLabel:()=> '12,400 / 200,000 tokens（6%）',rateLimitLabel:()=> 'codex · 300 分钟：剩余 82%',refreshRateLimits:async()=>{},resolvedModel:'gpt-6-astra',resolvedEffort:'medium',requests:new Map(),answer(id:string){this.requests.delete(id);view.update();}};
let attachments:{id:string;title:string;text:string}[]=[];
const notes=[{id:'20261001124824-pq6acxs',title:'项目研究笔记',text:'LOCAL_NOTE_5729'},{id:'20261001124825-abcdefg',title:'实验结果与下一步',text:'SECOND_NOTE_8910'}];
const tree=document.querySelector('#fixtures')!;
for(const note of notes){const item=document.createElement('div');item.className='b3-list-item';item.draggable=true;item.textContent=note.title;item.ondragstart=e=>e.dataTransfer!.setData('application/siyuan-file',note.id);tree.append(item);}
(window as any).previewActiveTab={id:'preview-active',title:notes[0].title,model:{editor:{protyle:{block:{rootID:notes[0].id}}}}};
const view=new ChatView(document.querySelector('#app')!,()=>chat,{send:async(text)=>{chat.session.workspaceLocked=true;chat.session.title='笔记整理';chat.session.messages.push({id:crypto.randomUUID(),role:'user',text,attachments:[...attachments]},{id:crypto.randomUUID(),role:'assistant',text:`已收到 **${attachments.length} 篇**参考笔记。\n\n${attachments.map(a=>'- '+a.title+'：`'+a.text+'`').join('\n')}\n\n这是交互测试中的模拟回复，未调用模型。`});attachments=[];view.update();return true;},editMessage:async(id,text)=>{const i=chat.session.messages.findIndex((m:any)=>m.id===id);chat.session.messages=chat.session.messages.slice(0,i);chat.session.messages.push({id:crypto.randomUUID(),role:'user',text},{id:crypto.randomUUID(),role:'assistant',text:'已根据编辑后的消息重新生成（模拟）。',phase:'final_answer'});view.update();},branch:async id=>{const i=chat.session.messages.findIndex((m:any)=>m.id===id);chat.session={...chat.session,id:crypto.randomUUID(),title:'示例分支',messages:structuredClone(chat.session.messages.slice(0,i+1))};view.update();},stop:()=>{chat.busy=false;view.update();},settings:()=>{},directory:anchor=>openWorkspaces(anchor),model:anchor=>openModels(anchor),effort:anchor=>openModels(anchor,true),permission:anchor=>{const p=openPopover(anchor,'审批方式');if(p)permissionPanel(p,chat.settings.permissionMode,async mode=>{chat.settings.permissionMode=mode;view.update();});},newChat:()=>{chat.session={id:crypto.randomUUID(),title:'新对话',workspaceMode:'auto',messages:[]};chat.settings.cwd='/Users/demo/Documents/Codex/2026-10-02/siyuan-'+chat.session.id;attachments=[];view.update();},select:()=>{},list:()=>[chat.session,{id:'history-research',title:'论文研究讨论'},{id:'history-results',title:'实验结果复盘'}],activeTabContext:()=>chat.settings.activeTabContext===true,setActiveTabContext:async enabled=>{chat.settings.activeTabContext=enabled;view.update();},models:async()=>catalog,quickSetting:async patch=>{Object.assign(chat.settings,patch);if(patch.reasoningEffort)chat.resolvedEffort=patch.reasoningEffort;view.update();},searchNotes:async query=>notes.filter(n=>n.title.includes(query)),referenceConversation:async id=>{attachments.push({title:'对话 · '+(id==='history-research'?'论文研究讨论':'实验结果复盘'),text:'历史对话参考内容'} as any);view.update();},attach:()=>{attachments.push(notes[0]);view.update();},clear:()=>{},context:()=>'',attachments:()=>attachments,removeAttachment:i=>{attachments.splice(i,1);view.update();},drop:async ids=>{for(const id of ids){const note=notes.find(n=>n.id===id);if(note&&!attachments.some(a=>a.id===id))attachments.push(note);}view.update();},workspace:()=>'/tmp/fixture',error:message=>alert(message)});

for(const width of [280,400,720]){const b=document.createElement('button');b.textContent=width+' px';b.onclick=()=>{document.querySelector<HTMLElement>('#app')!.style.width=width+'px';};tree.append(b);}

let active:ComposerPopover|undefined;
function openPopover(anchor:HTMLElement,title:string){if(active?.anchor===anchor&&!active.closed){active.close();return;}active?.close(false);return active=new ComposerPopover(anchor,title);}
const catalog=['GPT-6.1 Sol','GPT-6 Astra','GPT-6 Sol','GPT-6 Luna','GPT-5.6 Sol','GPT-5.6 Terra','GPT-5.6 Luna','GPT-5.5'].map(name=>({model:name.toLowerCase().replaceAll(' ','-'),displayName:name,defaultReasoningEffort:'medium',supportedReasoningEfforts:['low','medium','high','xhigh','max'].map(reasoningEffort=>({reasoningEffort}))}));
function openModels(anchor:HTMLElement,effort=true){const p=openPopover(anchor,'模型与思考强度');if(!p)return;
 const showEffort=(m:typeof catalog[number])=>effortPanel(p,m,chat.settings.reasoningEffort,async value=>{chat.settings.reasoningEffort=value;view.update();},list,{enabled:chat.settings.fastMode||false,set:async value=>{chat.settings.fastMode=value;},reset:async()=>{chat.settings.fastMode=false;chat.settings.reasoningEffort=m.defaultReasoningEffort;view.update();}});
 const list=()=>modelPanel(p,catalog,chat.settings.model,async m=>{chat.settings.model=m.model;chat.settings.modelName=m.displayName;showEffort(m as typeof catalog[number]);view.update();});
 if(effort)showEffort(catalog.find(m=>m.model===chat.settings.model)||catalog[1]);else list();}

const demo=document.createElement('button');demo.textContent='会话样式示例';demo.onclick=()=>{chat.session.messages=[{id:'demo-user',role:'user',text:'请总结这些笔记',elapsedMs:422000},{id:'demo-progress',role:'assistant',phase:'commentary',text:'我会先读取笔记，再归纳共同结论。'},{id:'demo-tool',role:'tool',text:'思源 MCP · 读取笔记\n已读取 2 篇笔记。',status:'completed'},{id:'demo-final',role:'assistant',phase:'final_answer',text:'已整理笔记要点：\n\n- 两组实验结果趋势一致。\n- 下一步补充对照实验并记录配置。\n\n这是界面预览中的模拟回复。'}];view.update();};tree.append(demo);

const queueDemo=document.createElement('button');queueDemo.textContent='消息排队示例';queueDemo.onclick=()=>{chat.busy=true;chat.turnId='demo-turn';chat.session.queuePaused=false;chat.session.queue=[{id:'queued-demo',text:'请只调整消息布局，保留原有功能。',displayText:'请只调整消息布局，保留原有功能。',attachments:[notes[0]]}];chat.pauseQueue=(v=true)=>{chat.session.queuePaused=v;view.update();};chat.removeQueued=(id:string)=>{chat.session.queue=chat.session.queue.filter((q:any)=>q.id!==id);view.update();};chat.editQueued=(id:string,text:string)=>{const q=chat.session.queue.find((q:any)=>q.id===id);q.text=q.displayText=text;view.update();};chat.steerQueued=async(id:string)=>{chat.session.messages.push({id:crypto.randomUUID(),role:'user',text:chat.session.queue.find((q:any)=>q.id===id).text,status:'steered'});chat.removeQueued(id);};view.update();};tree.append(queueDemo);

let workspaceBinding:string|undefined;
function openWorkspaces(anchor:HTMLElement){
 const pop=openPopover(anchor,'工作目录');if(!pop)return;
 const doc={id:notes[0].id,title:notes[0].title,ancestors:[notes[0].id]};
 workspacePanel(pop,{cwd:chat.settings.cwd,standalone:chat.settings.cwd.startsWith('/Users/demo/Documents/Codex/'),locked:!!chat.session.workspaceLocked,automatic:chat.session.workspaceMode==='auto',document:doc,binding:workspaceBinding?{docID:doc.id,title:doc.title,cwd:workspaceBinding}:undefined,recent:['/Users/demo/Documents/项目研究','/Users/demo/Documents/实验结果']},{choose:async cwd=>{if(!cwd.startsWith('/'))throw Error('请选择存在的本机绝对路径。');chat.settings.cwd=cwd;chat.session.workspaceMode='manual';view.update();},follow:async()=>{chat.settings.cwd=workspaceBinding||'/Users/demo/Documents/Codex/2026-10-02/siyuan-'+chat.session.id;chat.session.workspaceMode='auto';chat.session.workspaceBinding=workspaceBinding?doc.title:undefined;view.update();},bind:async(_doc,cwd)=>{workspaceBinding=cwd;if(!chat.session.workspaceLocked&&chat.session.workspaceMode==='auto'){chat.settings.cwd=cwd;chat.session.workspaceBinding=doc.title;}view.update();},unbind:async()=>{workspaceBinding=undefined;chat.session.workspaceBinding=undefined;view.update();},browse:async()=>'/Users/demo/Documents/项目研究'});
}
